name: Commitlint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Make commitlint.config.mjs executable
        run: chmod +x gqs/commitlint.config.mjs

      - name: Run Commitlint
        run: sudo npx commitlint --from=HEAD~1
