name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'         
        distribution: 'adopt'  

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Build with Maven
      run: mvn -B package -f gqs/pom.xml

    - name: Run tests
      run: mvn -B test -f gqs/pom.xml

    - name: Install commitlint
      run: npm install -g @commitlint/cli

    - name: Validate commits
      run: sudo npx commitlint --from=HEAD~1

    - name: Generate Semantic Version
      run: npx semantic-release

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: gqs
        path: gqs/target/gqs-1.0-SNAPSHOT.jar
